#***************************************************************
# Configuration file for preparing WRF simulation directories
#
# The approach is to create a directory for every simulation initial time
# All of the appropriate namelists, executables, scripts etc 
# are linked or copied into subdirectories.  
# 
# This is the top level configuration file for running 
# automated WRF forecasts. This will overide a small number
# of  settings in 'namelist.wps' and 'namelist.input'
#
# Environment variables can be accessed using $(var) syntax
# Local variables defined elswhere in this configuration file can be 
# accessed using %(var) syntax.  If the variable inside $() or %() 
# is not defined within the current environment, it will not be expanded.
#
# Due to the syntax of yaml, entries cannot begin with %; 
# to start an entry with a local variable reference, enclose 
# the entry in quotation marks, see examples below.
# 
# Although the file is nominally divided into sections by comments,
# logically it is a single dictionary 
#
#***************************************************************

#************************************************
# Timing
#************************************************
%[timing.yaml]


#************************************************
# List missing files
#************************************************
missing_files : $(PWD)/missing.txt
ok_files      : $(PWD)/ok.txt


#************************************************
# Directory locations  
#************************************************
base_dir          : $(PWD)                                            # assume configuration file has been copied into base directory
working_dir       : "%(base_dir)/%iY-%im-%id_%iH"                     # name simulation directories according to initial time
wrftools_dir      : $(HOME)/code/wrftools/devel                       # location of the code and templates
namelist_wps      : "%(base_dir)/namelist.wps"                  # location of namelist.wps template to use, assume in base directory
namelist_input    : "%(base_dir)/namelist.input"                # location of namelist.input template to use, assume in base directory
grb_dir           : /project/data/grib/GFS                      # used in ungrib sections   
sst_dir           : /project/data/grib/SST                      # used in ungrib section

  
#**********************************************************************************************
# Ungrib bondary condition job specifications. Allows ungrib to be run with different
# namelist.wps settings, such as different simulation length and start and end dates
#**********************************************************************************************
            
ungrib:
    GFS: 
        files     : "%(grb_dir)/GFS_Global_0p5deg_%iy%im%id_%iH%iM_fh%fH.grb"             # boundary condition file name specifiers
        delay     : 0                                                                     # any additional delay to apply to initial time e.g. delayed SST fields
        cycles    : [0,6,12,18]                                                           # restrict initial time to these hours
        ungrib_len: "%(simulation_len)"                                                   # allow different simulaton length for each ungrib task
        vtable    : "%(wps_dir)/ungrib/Variable_Tables/Vtable.GFS_old"                    # Vtable to use
        run_dir   : "%(working_dir)/ungrib"                                               # directory to run from 

        
    SST: 
        files     : "%(sst_dir)/rtg_sst_grb_hr_0.083.%iY%im%id"
        delay     : 24
        cycles    : [0]
        ungrib_len: 0
        run_dir   : "%(working_dir)/ungrib_sst"
        vtable    : "%(wps_dir)/ungrib/Variable_Tables/Vtable.SST"
