#***************************************************************
# Configuration file for downloading boundary conditions
#
# This is the top level configuration file for running 
# automated WRF forecasts. This will overide a small number
# of  settings in 'namelist.wps' and 'namelist.input'
#
# Environment variables can be accessed using $(var) syntax
# Local variables defined elswhere in this configuration file can be 
# accessed using %(var) syntax.  If the variable inside $() or %() 
# is not defined within the current environment, it will not be expanded.
#
# Due to the syntax of yaml, entries cannot begin with %; 
# to start an entry with a local variable reference, enclose 
# the entry in quotation marks, see examples below.
# 
# Although the file is nominally divided into sections by comments,
# logically it is a single dictionary 
#
#***************************************************************


#************************************************
# Running
#************************************************
dry_run           : false                   # if true don't run commands, just log them

#************************************************
# Directory locations  
#************************************************
base_dir          : $(PWD)                                            # assume configuration file has been copied into base directory
gfs_dir           : $(HOME)/GFS                      # used in ungrib sections   
sst_dir           : /project/data/grib/SST                      # used in ungrib section

#************************************************
# Servers
#************************************************
TOC      : weather.noaa.gov
NCEP     : ftp.ncep.noaa.gov
EMC      : ftp.emc.ncep.noaa.gov
STRC     : soostrc.comet.ucar.edu
STRCO    : soostrc.comet.ucar.edu
POLAR    : polar.ncep.noaa.gov
NOMAD    : nomads.ncep.noaa.gov
NOMADO   : nomads.ncep.noaa.gov
NOMAD3   : nomad3.ncep.noaa.gov
NOMAD4   : nomad4.ncep.noaa.gov
NOMAD5   : nomad5.ncep.noaa.gov
NOMAD6   : nomads6.ncdc.noaa.gov
NCDC     : nomads.ncdc.noaa.gov
POLAR    : polar.ncep.noaa.gov


#************************************************
# File specifications
#************************************************
fetch:
    GFS : 
        delay        : 0
        cycles       : [0,6,12,18] 
        length       : 72
        interval     : 3
        remote_files : 
            #- "http://%(NOMAD)/pub/data/nccf/com/gfs/prod/gfs.%iY%im%id%iH/gfs.t%iHz.pgrb2.0p50.f0%fH"
            #- "http://%(STRC)/pub/data/nccf/com/gfs/prod/gfs.%iY%im%id%iH/gfs.t%iHz.pgrb2.0p50.f0%fH"
            - "http://%(STRC)/data/grib/gfs/%iY%im%id/grib.t%iHz/%iy%im%id%iH.gfs.t%iHz.0p50.pgrb2f0%fH"
        local_files  : "%(gfs_dir)/GFS_Global_0p5deg_%iy%im%id_%iH%iM_fh%fH.grb"
    
    SST : 
        delay        : 24
        cycles       : [0] 
        length       : 0
        interval     : 0
        servers      : [NOMADS, STRC]
        remote_files : 
            - "ftp://%(POLAR)/pub/history/sst/ophi/rtg_sst_grb_hr_0.083.%iY%im%id"
        local_files  : "/project/data/grib/SST/rtg_sst_grb_hr_0.083.%iY%im%id"
        
#************************************************
# Logging
#************************************************
log.name          : wrf_forecast                           # name of logger object
log.level         : DEBUG                                  # log level to write to file   
log.file          : "%(base_dir)/prepare.log"              # file to write to
log.fmt           : "%(message)s"                          # see logging module for format codes
log.mail          : false                                  # send an email of logfile
log.mail.to       : sam.hawkins@vattenfall.com
log.mail.level    : INFO                                   # level to mail
log.mail.buffer   : 100000                                 # maximum number of lines in one email
log.mail.subject  : "WRF preparation log"                  # subject to use in email 
