#***************************************************************
# Script generation configuration file. 
# Generate's basic job scripts from templates
# 
# Environment variables can be accessed using $(var) syntax
# Local variables defined elswhere in this configuration file can be 
# accessed using %(var) syntax.  If the variable inside $() or %() 
# is not defined within the current environment, it will not be expanded.
#
# Due to the syntax of yaml, entries cannot begin with %; 
# to start an entry with a local variable reference, enclose 
# the entry in quotation marks, see examples below.
# 
# Although the file is nominally divided into sections by comments,
# logically it is a single dictionary 
#
#***************************************************************


#************************************************
# Logging
#************************************************
log.name          : wrf_forecast                           # name of logger object
log.level         : DEBUG                                  # log level to write to file   
log.file          : "%(base-dir)/forecast.log"             # file to write to
log.fmt           : "%(message)s"                          # see logging module for format codes
log.mail          : true                                   # send an email of log
log.mail.to       : sam.hawkins@vattenfall.com
log.mail.level    : INFO                                   # level to mail
log.mail.buffer   : 100000                                 # maximum number of lines in one email

#************************************************
# Directory locations  
#************************************************
wrftools-dir      : $(HOME)/code/wrftools/devel
template-dir      : "%(wrftools-dir)/templates"                 # location of script templates
base-dir          : $(HOME)/forecasting/test
target-dir        : "%(base-dir)/scripts"
working-dir       : "%(base-dir)/%iY-%im-%id_%iH"  
queue             : all.q

jobs:
    1: 
        template : "%(template-dir)/template_mpi.sge"
        target   : "%(target-dir)/ungrib/ungrib.sh"
        replacements: 
            <jobname>    : ungrib
            <executable> : ungrib.exe
            <nprocs>     : 1
            <queue>      : "%(queue)"
            <logfile>    : "%(working-dir)/ungrib/ungrib.log"

            
    2: 
        template : "%(template-dir)/template_mpi.sge"
        target   : "%(target-dir)/ungrib_sst/ungrib.sh"
        replacements: 
            <jobname>    : ungrib_sst
            <executable> : ungrib.exe
            <nprocs>     : 1
            <queue>      : "%(queue)"
            <logfile>    : "%(working-dir)/ungrib_sst/ungrib.log"            
            
    3: 
        template : "%(template-dir)/template_mpi.sge"
        target   : "%(target-dir)/metgrid/metgrid.sh"
        replacements: 
            <jobname>    : metgrid
            <executable> : metgrid.exe
            <nprocs>     : 1
            <queue>      : "%(queue)"
            <logfile>    : "%(working-dir)/metgrid/metgrid.log"            

    4: 
        template : "%(template-dir)/template_mpi.sge"
        target   : "%(target-dir)/wrf/real.sh"
        replacements: 
            <jobname>    : real
            <executable> : real.exe
            <nprocs>     : 1
            <queue>      : "%(queue)"
            <logfile>    : "%(working-dir)/wrf/real.log"            

    5: 
        template : "%(template-dir)/template_mpi.sge"
        target   : "%(target-dir)/wrf/wrf.sh"
        replacements: 
            <jobname>    : wrf
            <executable> : wrf.exe
            <nprocs>     : 40
            <queue>      : "%(queue)"
            <logfile>    : "%(working-dir)/wrf/wrf.log"
            
    6: 
        template : "%(template-dir)/template_mpi.sge"
        target   : "%(target-dir)/options.ncl"
        replacements: 
            <base-dir>    : wrf
            