#***************************************************************
# Configuration file for initialising WRF simulation base directory
#
# The approach is to create a base directory, which will hold a collection 
# of simulation directories which all share the same major namelist options.
# Initialisation will also create a set of 'master' job scripts which will also 
# get copied into the simulation directories. These job scripts can be added to 
# and edited by hand to do more complex operations.
#
# 
# Environment variables can be accessed using $(var) syntax
# Local variables defined elswhere in this configuration file can be 
# accessed using %(var) syntax.  If the variable inside $() or %() 
# is not defined within the current environment, it will not be expanded.
#
# Due to the syntax of yaml, entries cannot begin with %; 
# to start an entry with a local variable reference, enclose 
# the entry in quotation marks, see examples below.
#
#***************************************************************


#************************************************
# Logging
#************************************************
log-file          : null
log-fmt           : "%(message)s"                          # see logging module for format codes
   
#************************************************
# Directory locations  
#************************************************
base-dir          : $(PWD)                                             # this will be taken from current working direcory
wrftools-dir      : $(HOME)/code/wrftools  


#*************************************************************************************************************************
# Copy and linking
#*************************************************************************************************************************

# these subdirectoies will get created     
initialise.create:
    - "%(base-dir)"
    - "%(base-dir)/scripts"
    - "%(base-dir)/wrfout"
    - "%(base-dir)/tseries"
    - "%(base-dir)/log"

initialise.remove:
    - "%(base-dir)/prepare.py"                                            # list of arguments to consecutive linux rm commands. Be careful!
    - "%(base-dir)/submit.py"
    - "-r %(base-dir)/scripts"

initialise.link:                                                          # list of arguments to consecutive linux ln -sf commands
  - "%(wrftools-dir)/check.py      %(base-dir)"
  - "%(wrftools-dir)/prepare.py     %(base-dir)"

initialise.copy:                                                           # list of arguments to consecutive linux cp commands
  - "-r %(wrftools-dir)/config            %(base-dir)"
  - "-r %(wrftools-dir)/scripts           %(base-dir)"
  - "-r %(wrftools-dir)/ncl               %(base-dir)"
  - " %(wrftools-dir)/run.sh              %(base-dir)"
  
