#***************************************************************
# Configuration file for initialising a simulation 'base_dir' 
#
# The base directory should contain contains the master:
#     namelist.input
#     namelist.wps 
#
# Initialisation will copy and link the relevant python 
# scripts for preparing and submitting simulations.
#
# A folder of skeleton scripts is also created under
#     base_dir/scripts
#
#  These job scripts can then be added to and edited by hand 
#
#***************************************************************


#************************************************
# Logging
#************************************************
log.name          : wrftools                               # name of logger object
log.level         : DEBUG                                  # log level to write to file   
log.file          : "%(base_dir)/init.log"                 # file to write to
log.fmt           : "%(message)s"                          # see logging module for format codes


#************************************************
# Metadata. 
# added as attributes to the output netcdf files. 
#************************************************
model_run         : $(PWD)
bdy_conditions    : GFS

    
#************************************************
# Directory locations  
#************************************************
base_dir          : $(PWD)                                             # this will be taken from current working direcory
wrftools_dir      : $(HOME)/code/wrftools  
ncl_scripts       : "%(wrftools_dir)/ncl"                              # NCL visualisation scripts
template_dir      : "%(wrftools_dir)/scripts"                          # location of job script skeletons
target_dir        : "%(base_dir)/scripts"                              # create 'master' job scripts for collection of simulations


#*************************************************************************************************************************
# Copy and linking
#*************************************************************************************************************************

# these subdirectoies will get created     
initialise.create:
    - "%(base_dir)"
    - "%(target_dir)"
    - "%(base_dir)/wrfout"
    - "%(base_dir)/tseries"
    

initialise.remove:
    - "%(base_dir)/prepare.py"                                            # list of arguments to consecutive linux rm commands. Be careful!
    - "%(base_dir)/submit.py"

initialise.link:                                                          # list of arguments to consecutive linux ln -sf commands
  - "%(wrftools_dir)/prepare.py     %(base_dir)"
  - "%(wrftools_dir)/submit.py      %(base_dir)"

initialise.copy:                                                           # list of arguments to consecutive linux cp commands
  - "%(wrftools_dir)/config/timing.yaml      %(base_dir)"
  - "%(wrftools_dir)/config/prepare.yaml     %(base_dir)"
  - "%(wrftools_dir)/config/submit.yaml      %(base_dir)"
  - "%(wrftools_dir)/config/options.ncl      %(base_dir)"
  - "%(wrftools_dir)/config/locations.csv    %(base_dir)"
  - "-r %(template_dir)/*                    %(target_dir)"
  - "-r %(ncl_scripts)/*                     %(target_dir)/ncl"
  - "%(wrftools_dir)/run.sh                  %(base_dir)"
  
