#***************************************************************
# WRF Forecast Simulation Submission configuration file
#***************************************************************

#************************************************
# Directory locations  
#************************************************
base-dir          : $(PWD)
working-dir       : "%(base-dir)/%iY-%im-%id_%iH"  
wrftools-dir      : $(HOME)/code/wrftools/devel                       # location of local wrftools repository

#************************************************
# Number of parallel simulations 
# **********************************************
parallel           : 2                       

#************************************************
# Timing  
#************************************************
%[timing.yaml]


#************************************************
# Logging
#************************************************
log.name          : wrf_forecast                           # name of logger object
log.level         : DEBUG                                  # log level to write to file   
log.file          : "%(base-dir)/submit.log"               # file to write to
log.fmt           : "%(message)s"                          # see logging module for format codes
log.mail          : true                                   # send an email of log
log.mail.to       : sam.hawkins@vattenfall.com
log.mail.level    : INFO                                   # level to mail
log.mail.buffer   : 100000                                 # maximum number of lines in one email
log.mail.subject  : "Maestro WRF log"                      # subject to use in email 


#***********************************************************
# Running 
#
# note which jobs are submitted is ultimately controlled
# by the `jobs` section below. This is just a convenient 
# way of turning groups of jobs on or off e.g.
# python submit.py --config=submit-yaml --visualise=false
#
#***********************************************************
dry-run           : false  # log commands, don't run them
wps               : true
wrf               : true
post              : true
tseries           : true
power             : true
ncdump            : true
visualise         : true
dispatch          : true
finalise          : true


jobs:
    - name     : geogrid
      run      : "%(geogrid)"
      script   : "%(working-dir)/geogrid/geogrid.sh"
      nprocs   : 1
      queue    : all.q
      pe       : ompi
      
    - name     : ungrib
      run      : "%(wps)"
      script   : "%(working-dir)/ungrib/ungrib.sh"
      queue    : all.q
      pe       : ompi
      nprocs   : 1
      after    : geogrid

    - name     : ungrib.post
      run      : "%(wps)"
      script   : "%(working-dir)/ungrib/ungrib.post.sh"
      queue    : all.q
      pe       : ompi
      nprocs   : 1
      after    : ungrib

    - name     : ungrib.sst
      run      : "%(wps)"
      script   : "%(working-dir)/ungrib_sst/ungrib.sh"
      after    : "ungrib*"
      queue    : all.q
      pe       : ompi
      nprocs   : 1
      after    : geogrid
      
    - name     : ungrib.sst.post
      run      : "%(wps)"
      script   : "%(working-dir)/ungrib_sst/ungrib_sst.post.sh"
      queue    : all.q
      pe       : ompi
      nprocs  : 1
      after    : ungrib.sst
      log      : ungrib.post.log        
       
    - name     : metgrid
      run      : "%(wps)"
      script   : "%(working-dir)/metgrid/metgrid.sh"
      queue    : all.q
      pe       : ompi
      nprocs  : 1
      after    : ungrib*
      
    - name   : real.pre
      run    : "%(wrf)"
      script : "%(working-dir)/wrf/real.pre.sh"
      queue  : all.q
      pe     : ompi
      nprocs : 1
      after  : metgrid
      log    : real.pre.log
      
    - name    : real
      run     : "%(wrf)"
      script  : "%(working-dir)/wrf/real.sh"
      queue   : all.q
      pe      : ompi
      nprocs  : 1
      after   : real.pre
    
    - name    : wrf
      run     : "%(wrf)"
      script  : "%(working-dir)/wrf/wrf.sh"
      queue   : all.q
      pe      : ompi
      nprocs  : 80
      after   : real
      log     : wrf.log

    - name   : ncl
      run    : "%(visualise)"
      script : "%(working-dir)/ncl.sh"
      queue  : all.q
      pe     : ompi
      nprocs : 1
      after  : wrf
      array  : "%(max_dom)"
      
      
    - name    : wrf.post
      run     : "%(post)"
      script  : "%(working-dir)/wrf/wrf.post.sh"
      queue   : all.q
      pe      : ompi
      nprocs  : 1
      after   : wrf,ncl
      array   : "%(max_dom)"

    - name   : tseries
      run    : "%(tseries)"
      script : "%(working-dir)/tseries.sh"
      queue  : all.q
      pe     : ompi
      nprocs : 1
      after  : wrf.post
      array  : "%(max_dom)"

    - name    : power
      run     : "%(power)"
      script  : "%(working-dir)/power.sh"
      queue   : all.q
      pe      : ompi
      nprocs  : 1
      after   : tseries
      array   : "%(max_dom)"


    - name    : ncdump
      run     : "%(ncdump)"
      script  : "%(working-dir)/ncdump.sh"
      queue   : all.q
      pe      : ompi
      nprocs  : 1
      after   : tseries,power
      array   : "%(max_dom)"

    - name    : dispatch
      run     : "%(dispatch)"
      script  : "%(working-dir)/dispatch.sh"
      queue   : graphics.q
      pe      : ompi
      nprocs  : 1 
      after   : ncl,wrf.post
      
    - name    : finalise
      run     : "%(finalise)"
      script  : "%(working-dir)/finalise.sh"
      queue   : all.q
      pe      : ompi
      nprocs  : 1
      after   : wrf.post,power,dispatch,ncdump
    
