#***************************************************************
# Timing
# If no start time is specified, the latest time is calculated
# from the system time, minus the delay in hours, rounded to the
# closest cycle time.
#
# To run a reforecast or a reanalysis, use start and end time.
#***************************************************************
max_dom            : 2                       # maximum number of nests, this will override namelists
history_interval   : 60                      # minutes between history writes
bdy_interval       : 3                       # hours between boundary conditions
simulation_length  : 72                      # total simulation length in hours
